blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from blog.views import blog_add

app_name = 'blog'
urlpatterns = [
    path('blog/add-blog/',views.add_blog,name='add_blog'),
    path('blog/add-topic/',views.add_topic,name='add_topic'),
    path('blog/topic/<int:id>/',views.topic_detail,name='topic_detail'),
    path('add-blog/',views.blog_add.as_view(),name='blog_add'),
    path('blog/<int:blogid>/preference/<int:userpreference>/',views.blogpreference,name='blogpreference'),
    path('blog/vote/<int:topicid>/preference/<int:userpreference>/',views.topicpreference,name='topicpreference'),
    path('blog/blog_list/',views.blog_list,name='blog_list'),
    path('blog/<category_slug>/',views.blog_list,name='blog_list_by_category'),
    path('blog/<int:id>/<slug>/',views.blog_detail,name='blog_detail'),
    path('my-blogs/',views.edit_list,name='edit_list'),
    path('archive-blog/<int:id>/',views.archive_blog, name='archive_blog'),
    path('publish-blog/<int:id>/',views.publish_blog, name='publish_blog'),
    path('edit-blog/<int:id>/',views.edit_blog, name='edit_blog'),
    path('create-category-blog/',views.create_category, name='create_category'),
]

home/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from shop.views import art_add

app_name = 'shop'
urlpatterns = [
    path('add-art/',views.add_art,name='add_art'),
    path('art/add-art/',views.art_add.as_view(),name='art_add'),
    path('art/<int:artid>/preference/<int:userpreference>/',views.artpreference,name='artpreference'),
    path('art/art_list',views.art_list,name='art_list'),
    path('art/<category_slug>/',views.art_list,name='art_list_by_category'),
    path('art/<int:id>/<slug>/',views.art_detail,name='art_detail'),
    path('bidding/<int:id>/<slug>/',views.bidding,name='bidding'),
    path('art/bidding/<int:id>/<slug>/',views.bidding_detail,name='bidding_detail'),
    
]

legends/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'legends'
urlpatterns = [
    path('<int:id>/',views.legend_detail,name='legend_detail'),
    path('legend/<int:legendid>/preference/<int:userpreference>/',views.legendpreference,name='legendpreference'),
    path('legend-list',views.legend_list,name='legend_list'),
    
]

orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('my-bids/',views.my_orders,name='my_orders'),
    path('order/<order_id>/',views.order_detail, name='order_detail'),
    path('order_update/<order_id>/',views.order_update,name='order_update'),
]

wasanii/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = 'home'),
    path('',include(('home.urls','home'),namespace='home')),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path('',include(('legends.urls','legends'),namespace='legends')),
    path('',include(('orders.urls','orders'),namespace='orders')),
    path('',include(('shop.urls','shop'),namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from home.models import ArtistProfile
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=20,db_index=True)
    slug = models.SlugField(max_length=150,db_index=True,unique=True)
    description = models.TextField()
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:art_list_by_category',args=[self.slug])
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

class Art(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    artist = models.ForeignKey(ArtistProfile,related_name='owner',on_delete=models.CASCADE)
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True,unique=True)
    image_1 = models.ImageField(upload_to='products/%Y/%m/%d')
    image_2 = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    bid_price = models.DecimalField(max_digits=10, decimal_places=2)
    likes= models.IntegerField(default=0)
    dislikes= models.IntegerField(default=0)
    available = models.BooleanField(default=False)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Art, self).save(*args, **kwargs)
    def get_art_url(self):
        return reverse('shop:art_detail',args=[self.id, self.slug])
    def go_bidding(self):
        return reverse('shop:bidding',args=[self.id, self.slug])

class Preference(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    art= models.ForeignKey(Art,on_delete=models.CASCADE)
    value= models.IntegerField()
    date= models.DateTimeField(auto_now= True)

    def __str__(self):
        return str(self.user) + ':' + str(self.art) +':' + str(self.value)
    class Meta:
        unique_together = ("user", "art", "value")

home/shop/forms.py
from django import forms
from orders.models import Order, Bids
from .models import Art
from home.models import ArtistProfile

class BiddingForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ['amount']
    def clean_bar(self):
        return self.cleaned_data['amount'] or None

"""class ArtAddForm(forms.ModelForm):
    class Meta:
        model = Art
        fields = ['category','name','image_1','bid_price','description']"""

class ArtAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(ArtAddForm, self).__init__(*args, **kwargs)
        artist = self.request.user.artistprofile
        self.fields['artist'].queryset = ArtistProfile.objects.filter(user = self.request.user)
    class Meta:
        model = Art
        fields = ['category','artist','name','image_1','bid_price','description']

home/shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.template import loader
from django.http import HttpResponse, Http404,HttpResponseRedirect
from .models import Category,Art,Preference
from orders.models import Order, Bids
from django.contrib.auth.decorators import login_required
from .forms import BiddingForm, ArtAddForm
from django.contrib.auth.models import User
from django.db.models import Max
from datetime import datetime,timedelta,date
from home.models import ArtistProfile
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

def art_list(request, category_slug=None):
    # get the list of all arts that can be bided on.
    template = loader.get_template('shop/art/list.html')
    category = None
    categories = Category.objects.all()
    arts = Art.objects.all()
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        arts = arts.filter(category=category)
    
    context = {'category':category,
                'categories':categories,
                'arts':arts,}
    return HttpResponse(template.render(context,request))

def art_detail(request, id, slug):
    # show the detail of an individual art that can be bided on.
    template = loader.get_template('shop/art/detail.html')
    art = get_object_or_404(Art,id=id,slug=slug)
    context = {'art': art,}
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def bidding_detail(request,id,slug):
    art = get_object_or_404(Art,id=id,slug=slug,available=True)
    bids = Bids.objects.filter(product = art).order_by('-created')
    bid_count = Bids.objects.filter(product = art).count()
    context = {'art': art,'bids':bids,'bid_count':bid_count}
    template = loader.get_template('shop/art/bidding.html')
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def bidding(request,id,slug):
    # the bidding process
    art = get_object_or_404(Art,id=id,slug=slug,available=True)
    start_date = art.updated
    end_bid_date = start_date + timedelta(days=7)
    tarehe = datetime.today()
    if start_date < tarehe < end_bid_date:
        bei = ''
        b_bei = art.bid_price + 1
        if request.method == 'POST':
            form = BiddingForm(request.POST)
            if form.is_valid():
                bid = form.cleaned_data.get('amount')
                if Bids.objects.filter(product = art).count() == 0:
                    bei = art.bid_price
                else:
                    bei = Bids.objects.filter(product = art).aggregate(Max('amount')).get('amount__max')
                
                if bid > art.bid_price:
                    bids = form.save(commit=False)
                    bids.bidder = request.user
                    bids.product = Art.objects.get(name=art.name,id=art.id)
                    bids.save()
        else:
            form = BiddingForm()
        a_bids = Bids.objects.order_by('-created').filter(product = art)[:15]
        context = {'art': art,'form':form,'a_bids':a_bids,'bei':bei,'b_bei':b_bei,}
        template = loader.get_template('shop/art/bidding.html')
        return HttpResponse(template.render(context,request))
    else:
        winner = ''
        bei = Bids.objects.filter(product = art).aggregate(Max('amount')).get('amount__max')
        top_bid = Bids.objects.filter(product = art,amount= bei).order_by('-created')
        winner = top_bid[0].bidder
        order = Order.objects.create(orderer = winner, product = art,cost=top_bid[0].amount)
        art.available = False
        art.save()
        return redirect('shop:art_list')

@login_required(login_url='/login/')
def add_art(request):
    # check if the user is an artist
    a = request.user
    b = ArtistProfile.objects.filter(user=a).count()
    if b == 1:
        return redirect('shop:art_add')
    else:
        return HttpResponse('Sorry.You are not registered as an artist.')
    
class art_add(CreateView):
    # adding an art
    model = Art
    form_class = ArtAddForm
    template_name = 'shop/add_art.html'
    success_url = reverse_lazy('shop:art_list')
    def get_form_kwargs(self):
        kwargs = super(art_add, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs 

@login_required(login_url='/login/')
def artpreference(request,artid, userpreference):
    if request.method == "POST":
        eachpost= get_object_or_404(Art, id=artid)
        aa = eachpost.id
        ss = eachpost.slug
        obj=''
        valueobj=''
        try:
            obj= Preference.objects.get(user= request.user, art= eachpost)
            valueobj= obj.value #value of userpreference
            valueobj= int(valueobj)
            userpreference= int(userpreference)
            if valueobj != userpreference:
                obj.delete()
                upref= Preference()
                upref.user= request.user
                upref.art= eachpost
                upref.value= userpreference
                if userpreference == 1 and valueobj != 1:
                    eachpost.likes += 1
                    eachpost.dislikes -=1
                elif userpreference == 2 and valueobj != 2:
                        eachpost.dislikes += 1
                        eachpost.likes -= 1
                upref.save()
                eachpost.save()
                return redirect('shop:art_detail',id=aa,slug=ss)

            elif valueobj == userpreference:
                obj.delete()
                if userpreference == 1:
                    eachpost.likes -= 1
                elif userpreference == 2:
                    eachpost.dislikes -= 1
                eachpost.save()
                return redirect('shop:art_detail',id=aa,slug=ss)
        except Preference.DoesNotExist:
            upref= Preference()
            upref.user= request.user
            upref.art= eachpost
            upref.value= userpreference
            userpreference= int(userpreference)
            if userpreference == 1:
                eachpost.likes += 1
            elif userpreference == 2:
                eachpost.dislikes +=1
            upref.save()
            eachpost.save()                            
            return redirect('shop:art_detail',id=aa,slug=ss)

    else:
        eachpost= get_object_or_404(Art, id=artid)
        return redirect('home')

home/shop/templates/shop/add_art.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Add Art
{% endblock %}
{% block content %}
<div class="container">
    {% load widget_tweaks %}
    <form method="post" novalidate enctype="multipart/form-data" action=".">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
    
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
            {% else %}
            {% render_field field class="form-control" %}
            {% endif %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 15px;">Sign in</button>
    </form>
</div>
{% endblock %}

home/shop/templates/shop/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <title>{% block title %}My shop{% endblock %}</title>
        <script>
            /* Set the width of the side navigation to 250px */
            function openNav() {
                document.getElementById("mySidenav").style.width = "250px";
                }
            /* Set the width of the side navigation to 0 */
            function closeNav() {
                document.getElementById("mySidenav").style.width = "0";
                }
        </script>
        <style>
            /* The side navigation menu */
            .sidenav {
                 height: 100%; /* 100% Full-height */
                 width: 0; /* 0 width - change this with JavaScript */
                position: fixed; /* Stay in place */
                z-index: 1; /* Stay on top */
                top: 0; /* Stay at the top */
                left: 0;
                background-color: #cccde7; /* Black*/
                overflow-x: hidden; /* Disable horizontal scroll */
                padding-top: 60px; /* Place content 60px from the top */
                margin-top: 65px;
                transition: 0.5s; /* 0.5 second transition effect to slide in the sidenav */
                border-top-right-radius: 5px;
                }

            /* The navigation menu links */
            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 15px;
                color: #312f2f;
                display: block;
                transition: 0.3s;
                }

            /* When you mouse over the navigation links, change their color */
            .sidenav a:hover {
                color: #6e326b;
                }

            /* Position and style the close button (top right corner) */
            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
                color: red;
                }

            /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
            #main {
                transition: margin-left .5s;
                padding: 20px;
                }

            /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
            @media screen and (max-height: 450px) {
                .sidenav {padding-top: 15px;}
                .sidenav a {font-size: 18px;}
                }
            .items{
                border: 1px blue solid; 
                background-color: white;
                padding: 3px;
                margin-bottom: 5px; 
                border-radius: 3px;
                transition: all .4s ease-in-out;
                box-shadow: 0 0 25px 0 rgba(20, 27, 202, .17);
            }
            .items:hover {
                box-shadow: 0 0 25px 0 rgba(20, 27, 201, .05);
                cursor: pointer;
                background-image: linear-gradient(-45deg, #d3cfeb 0%, #bbd0e2 100%)
            }
            .items:focus {
                box-shadow: 0 0 25px 0 rgba(20, 27, 201, .05);
                cursor: pointer;
                background-image: linear-gradient(-45deg, #ccc7e6 0%, #bed2e4 100%)
            }
            /*Floating Back-To-Top Button*/
    #topBtn {
        position: fixed;
        bottom: 10px;
        float: right;
        right: 10px;
        max-width: 40px;
        width: 100%;
        font-size: 12px;
        border-color: rgba(85, 85, 85, 0.2);
        background-color: rgb(100,100,100);
        padding: 3px;
        border-radius: 4px;

    }
/*On Hover Color Change*/
    #topBtn:hover {
        background-color: #7dbbf1;
    }
    .all{
        width: 100%;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }
        </style>
    </head>
    <body class="container-fluid bg-light">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top .navbar-expand{-sm|-md|-lg|-xl|-xxl}">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Art</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:art_list' %}" >List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:add_art' %}" >Add Art</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'orders:my_orders' %}" >My Bids</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'legends:legend_list' %}">Legends</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog_list' %}">Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:home' %}" >Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div style="padding-top: 55px;"></div>
        <div id="content";class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
        <button id="topBtn"><a href="#top" style="color: white; text-decoration: none;">Top</a></button>
    </body>
</html>