blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from blog.views import blog_add

app_name = 'blog'
urlpatterns = [
    path('blog/add-blog/',views.add_blog,name='add_blog'),
    path('blog/add-topic/',views.add_topic,name='add_topic'),
    path('blog/topic/<int:id>/',views.topic_detail,name='topic_detail'),
    path('add-blog/',views.blog_add.as_view(),name='blog_add'),
    path('blog/<int:blogid>/preference/<int:userpreference>/',views.blogpreference,name='blogpreference'),
    path('blog/vote/<int:topicid>/preference/<int:userpreference>/',views.topicpreference,name='topicpreference'),
    path('blog/blog_list/',views.blog_list,name='blog_list'),
    path('blog/<category_slug>/',views.blog_list,name='blog_list_by_category'),
    path('blog/<int:id>/<slug>/',views.blog_detail,name='blog_detail'),
    path('my-blogs/',views.edit_list,name='edit_list'),
    path('archive-blog/<int:id>/',views.archive_blog, name='archive_blog'),
    path('publish-blog/<int:id>/',views.publish_blog, name='publish_blog'),
    path('edit-blog/<int:id>/',views.edit_blog, name='edit_blog'),
    path('create-category-blog/',views.create_category, name='create_category'),
]

home/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from shop.views import art_add

app_name = 'shop'
urlpatterns = [
    path('add-art/',views.add_art,name='add_art'),
    path('art/add-art/',views.art_add.as_view(),name='art_add'),
    path('art/<int:artid>/preference/<int:userpreference>/',views.artpreference,name='artpreference'),
    path('art/art_list',views.art_list,name='art_list'),
    path('art/<category_slug>/',views.art_list,name='art_list_by_category'),
    path('art/<int:id>/<slug>/',views.art_detail,name='art_detail'),
    path('bidding/<int:id>/<slug>/',views.bidding,name='bidding'),
    path('art/bidding/<int:id>/<slug>/',views.bidding_detail,name='bidding_detail'),
    
]

home/urls.py
from django.urls import path,reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
app_name = 'home'
urlpatterns = [
    path('',views.home,name = 'home'),
    path('artist-register/',views.artist_register,name='artist_register'),
    path('writer-register/',views.writer_register,name='writer_register'),
    path('buyer-register/',views.buyer_register,name='buyer_register'),
    path('login/',views.log_in,name='log_in'),
    path('logout/',views.log_out,name='log_out'),
    path('artist/<int:id>/',views.artist_detail,name='artist_detail'),
    path('writer/<int:id>/',views.writer_detail,name='writer_detail'),
] 

legends/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'legends'
urlpatterns = [
    path('<int:id>/',views.legend_detail,name='legend_detail'),
    path('legend/<int:legendid>/preference/<int:userpreference>/',views.legendpreference,name='legendpreference'),
    path('legend-list',views.legend_list,name='legend_list'),
    
]

wasanii/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = 'home'),
    path('',include(('home.urls','home'),namespace='home')),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path('',include(('legends.urls','legends'),namespace='legends')),
    path('',include(('orders.urls','orders'),namespace='orders')),
    path('',include(('shop.urls','shop'),namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/forms.py
from django import forms
from .models import ArtistProfile,WriterProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ExtendedUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=60)
    last_name = forms.CharField(max_length=60)
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2']
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        
        if commit:
            user.save()
        return user

class ArtistProfileForm(forms.ModelForm):
    class Meta:
        model = ArtistProfile
        fields = ['county','town','phone_number','description'] 

class WriterProfileForm(forms.ModelForm):
    class Meta:
        model = WriterProfile
        fields = ['age','town','phone_number','description'] 

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

home/shop/forms.py
from django import forms
from orders.models import Order, Bids
from .models import Art
from home.models import ArtistProfile

class BiddingForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ['amount']
    def clean_bar(self):
        return self.cleaned_data['amount'] or None

"""class ArtAddForm(forms.ModelForm):
    class Meta:
        model = Art
        fields = ['category','name','image_1','bid_price','description']"""

class ArtAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(ArtAddForm, self).__init__(*args, **kwargs)
        artist = self.request.user.artistprofile
        self.fields['artist'].queryset = ArtistProfile.objects.filter(user = self.request.user)
    class Meta:
        model = Art
        fields = ['category','artist','name','image_1','bid_price','description']

home/shop/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.template import loader
from django.http import HttpResponse, Http404,HttpResponseRedirect
from .models import Category,Art,Preference
from orders.models import Order, Bids
from django.contrib.auth.decorators import login_required
from .forms import BiddingForm, ArtAddForm
from django.contrib.auth.models import User
from django.db.models import Max
from datetime import datetime,timedelta,date
from home.models import ArtistProfile
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

def art_list(request, category_slug=None):
    # get the list of all arts that can be bided on.
    template = loader.get_template('shop/art/list.html')
    category = None
    categories = Category.objects.all()
    arts = Art.objects.all()
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        arts = arts.filter(category=category)
    
    context = {'category':category,
                'categories':categories,
                'arts':arts,}
    return HttpResponse(template.render(context,request))

def art_detail(request, id, slug):
    # show the detail of an individual art that can be bided on.
    template = loader.get_template('shop/art/detail.html')
    art = get_object_or_404(Art,id=id,slug=slug)
    context = {'art': art,}
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def bidding_detail(request,id,slug):
    art = get_object_or_404(Art,id=id,slug=slug,available=True)
    bids = Bids.objects.filter(product = art).order_by('-created')
    bid_count = Bids.objects.filter(product = art).count()
    context = {'art': art,'bids':bids,'bid_count':bid_count}
    template = loader.get_template('shop/art/bidding.html')
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def bidding(request,id,slug):
    # the bidding process
    art = get_object_or_404(Art,id=id,slug=slug,available=True)
    start_date = art.updated
    end_bid_date = start_date + timedelta(days=7)
    tarehe = datetime.today()
    if start_date < tarehe < end_bid_date:
        bei = ''
        b_bei = art.bid_price + 1
        if request.method == 'POST':
            form = BiddingForm(request.POST)
            if form.is_valid():
                bid = form.cleaned_data.get('amount')
                if Bids.objects.filter(product = art).count() == 0:
                    bei = art.bid_price
                else:
                    bei = Bids.objects.filter(product = art).aggregate(Max('amount')).get('amount__max')
                
                if bid > art.bid_price:
                    bids = form.save(commit=False)
                    bids.bidder = request.user
                    bids.product = Art.objects.get(name=art.name,id=art.id)
                    bids.save()
        else:
            form = BiddingForm()
        a_bids = Bids.objects.order_by('-created').filter(product = art)[:15]
        context = {'art': art,'form':form,'a_bids':a_bids,'bei':bei,'b_bei':b_bei,}
        template = loader.get_template('shop/art/bidding.html')
        return HttpResponse(template.render(context,request))
    else:
        winner = ''
        bei = Bids.objects.filter(product = art).aggregate(Max('amount')).get('amount__max')
        top_bid = Bids.objects.filter(product = art,amount= bei).order_by('-created')
        winner = top_bid[0].bidder
        order = Order.objects.create(orderer = winner, product = art,cost=top_bid[0].amount)
        art.available = False
        art.save()
        return redirect('shop:art_list')

@login_required(login_url='/login/')
def add_art(request):
    # check if the user is an artist
    a = request.user
    b = ArtistProfile.objects.filter(user=a).count()
    if b == 1:
        return redirect('shop:art_add')
    else:
        return HttpResponse('Sorry.You are not registered as an artist.')
    
class art_add(CreateView):
    # adding an art
    model = Art
    form_class = ArtAddForm
    template_name = 'shop/add_art.html'
    success_url = reverse_lazy('shop:art_list')
    def get_form_kwargs(self):
        kwargs = super(art_add, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs 

@login_required(login_url='/login/')
def artpreference(request,artid, userpreference):
    if request.method == "POST":
        eachpost= get_object_or_404(Art, id=artid)
        aa = eachpost.id
        ss = eachpost.slug
        obj=''
        valueobj=''
        try:
            obj= Preference.objects.get(user= request.user, art= eachpost)
            valueobj= obj.value #value of userpreference
            valueobj= int(valueobj)
            userpreference= int(userpreference)
            if valueobj != userpreference:
                obj.delete()
                upref= Preference()
                upref.user= request.user
                upref.art= eachpost
                upref.value= userpreference
                if userpreference == 1 and valueobj != 1:
                    eachpost.likes += 1
                    eachpost.dislikes -=1
                elif userpreference == 2 and valueobj != 2:
                        eachpost.dislikes += 1
                        eachpost.likes -= 1
                upref.save()
                eachpost.save()
                return redirect('shop:art_detail',id=aa,slug=ss)

            elif valueobj == userpreference:
                obj.delete()
                if userpreference == 1:
                    eachpost.likes -= 1
                elif userpreference == 2:
                    eachpost.dislikes -= 1
                eachpost.save()
                return redirect('shop:art_detail',id=aa,slug=ss)
        except Preference.DoesNotExist:
            upref= Preference()
            upref.user= request.user
            upref.art= eachpost
            upref.value= userpreference
            userpreference= int(userpreference)
            if userpreference == 1:
                eachpost.likes += 1
            elif userpreference == 2:
                eachpost.dislikes +=1
            upref.save()
            eachpost.save()                            
            return redirect('shop:art_detail',id=aa,slug=ss)

    else:
        eachpost= get_object_or_404(Art, id=artid)
        return redirect('home')

home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.template import loader
from django.http import HttpResponse, Http404,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import ExtendedUserCreationForm,ArtistProfileForm,LoginForm,WriterProfileForm
from .models import ArtistProfile,WriterProfile
from shop.models import Art
from blog.models import Blog
from django.contrib.auth.models import User

def home(request):
    if request.user.is_authenticated: 
        username = request.user.username
    else:
        username = 'not logged in'
    context = {'username':username,}
    template = loader.get_template('home/home2.html')
    return HttpResponse(template.render(context,request))


def artist_register(request):
    template = loader.get_template('home/artist_register.html')
    if request.method == 'POST':
        form =ExtendedUserCreationForm(request.POST)
        profile_form = ArtistProfileForm(request.POST)
        
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            
            profile.save()
            
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1') 
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('home')
    else:
        form = ExtendedUserCreationForm()
        profile_form = ArtistProfileForm()
    
    context = {'form':form,'profile_form':profile_form}
    return HttpResponse(template.render(context,request))

def writer_register(request):
    template = loader.get_template('home/writer_register.html')
    if request.method == 'POST':
        form =ExtendedUserCreationForm(request.POST)
        writer_form = WriterProfileForm(request.POST)
        
        if form.is_valid() and writer_form.is_valid():
            user = form.save()
            age = writer_form.cleaned_data.get('age')
            town = writer_form.cleaned_data.get('town')
            phone = writer_form.cleaned_data.get('phone_number')
            description = writer_form.cleaned_data.get('description')
            WriterProfile.objects.create(user= user,
                                        age = age,
                                        town = town,
                                        phone_number = phone,
                                        description = description)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1') 
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('home')
    else:
        form = ExtendedUserCreationForm()
        writer_form = WriterProfileForm()
    
    context = {'form':form,'writer_form':writer_form}
    return HttpResponse(template.render(context,request))

def buyer_register(request):
    template = loader.get_template('home/buyer_register.html')
    if request.method == 'POST':
        form =ExtendedUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1') 
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('home')
    else:
        form = ExtendedUserCreationForm()
    
    context = {'form':form,}
    return HttpResponse(template.render(context,request))

def log_in(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect ('home')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
        else:
            form = LoginForm()
    form = LoginForm()
    template = loader.get_template('home/login.html')
    context = {'form':form}
    return HttpResponse(template.render(context,request))

def log_out(request):
    logout(request)
    return redirect('home')

def artist_detail(request,id):
    artist = get_object_or_404(ArtistProfile,id=id)
    a = User.objects.get(username=artist)
    full_name = a.first_name + ' ' + a.last_name
    art = Art.objects.filter(artist=artist)
    template = loader.get_template('home/artist.html')
    context = {'artist':artist,'art':art,'full_name':full_name,'a':a}
    return HttpResponse(template.render(context,request))

def writer_detail(request,id):
    writer = get_object_or_404(WriterProfile,id=id)
    a = User.objects.get(username=writer)
    full_name = a.first_name + ' ' + a.last_name
    blog = Blog.objects.filter(writer = writer)
    template = loader.get_template('home/writer.html')
    context = {'writer':writer,'blog':blog,'full_name':full_name,'a':a}
    return HttpResponse(template.render(context,request))

home/templates/home/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <title>{% block title %}Accounts{% endblock %}</title>
    </head>
    <body class="container-fluid bg-light">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top .navbar-expand{-sm|-md|-lg|-xl|-xxl}">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Accounts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:log_in' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:artist_register' %}" >Artist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:writer_register' %}" >Writer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:buyer_register' %}" >User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:log_out' %}" >Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div style="padding-top: 55px;"></div>
        <div id="content";class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>wasanii</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

</head>
<body class="container-fluid bd-light">
    
    <div style="color: blue; text-align: center;">
        Register as: <br>
        <a href="{% url 'home:artist_register' %}" style="text-decoration: none; margin: 10px;"> <button class="btn btn-primary" style="margin: 10px;">Artist</button></a> <br>
        <a href="{% url 'home:writer_register' %}" style="text-decoration: none;"><button class="btn btn-primary" style="margin: 10px;">Writer</button></a> <br>
        <a href="{% url 'home:buyer_register' %}" style="text-decoration: none;"> <button class="btn btn-primary" style="margin: 10px;">User</button></a> <br>
    </div>
    <div style="text-align: center;">
        {% if user.is_authenticated %} 
        <h3>{{username}}</h3>
        {% else %}
            <a href="{% url 'home:log_in' %}" style="text-decoration: none;"> <button class="btn btn-success">LOGIN</button></a>
        {% endif %}
        </div>
    <div style="text-align: center;">
        <a href="{% url 'shop:art_list' %}" style="text-decoration: none;"> <button class="btn btn-warning" style="margin: 10px;">ARTS</button></a> <br>
        <a href="{% url 'blog:blog_list' %}" style="text-decoration: none;"> <button class="btn btn-warning" style="margin: 10px;">BLOGS </button> </a> <br>
        <a href="{% url 'legends:legend_list' %}" style="text-decoration: none;"> <button class="btn btn-warning" style="margin: 10px;">LEGENDS </button> </a> <br>
    </div>
    <div style="text-align: center;">
        {% if request.user.is_superuser %}
            <a href="{% url 'blog:create_category' %}"> <button class="btn btn-danger btn-sm">Category</button></a>
        {% endif %}
    </div>
</body>
</html>

home/templates/home/home2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FREENTY</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <style>
        .intro{
            font-size: 40px;
            text-align: center;
            font-weight: 500;
        }
        .intro2{
            text-align: center;
        }
        .blog{
            text-align: center;
        }
        .blog1{
            color: whitesmoke;
            font-size: 30px;
            font-weight: 500;
            background-color: rgb(109, 109, 243);
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }
        .blog2{
            color: rgb(109, 109, 243);
            background-color: whitesmoke;
            font-weight: 500;
        }
        .acc{
            text-align: center;
        }
        .acc0{
            color: white;
            font-size: 30px;
            font-weight: 500;
            background-color: brown;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }
        .acc2{
            color: brown;
            background-color: white;
            font-weight: 500;
        }
        .contact{
            text-align: center;
        }
        .contact1{
            color: white;
            font-size: 30px;
            font-weight: 500;
            background-color: rgb(43, 184, 43);
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }
        .tt{
            color: rgb(6, 6, 15);
            font-size: 30px;
            font-weight: 500;
            padding-top: 10px;
        }
        .linki{
            width: fit-content;
            background-color: rgb(109, 109, 243);
            padding: 10px;
            border-radius: 5px;
        }
    </style>
</head>
<body style="font-size:larger">
    <div class="intro">FREENTY</div>
    <div class="intro2">
        Everything but nothing is nothing but everything.
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="blog">
                    <a href="{% url 'blog:blog_list' %}" style="text-decoration: none;">
                        <div class="blog1">BLOG</div>
                        <div class="blog2">
                            Interesting and boring posts. <br>
                            Captivating and repelling stories. <br> 
                            What is your perspective?
                        </div>
                        <img src="https://wallpapercave.com/wp/wp8276647.jpg" alt="blogs" style="width: 100%; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                        </a>
                </div> <br>
            </div>
            <div class="col-sm">
                <div class="acc">
                    <div class="acc0">ACCOUNTS</div>
                <div class="acc1">
                    {% if user.is_authenticated %} 
                        <div style="background-color: rgb(209, 233, 236);">
                            <h3>{{username}}</h3>
                            <span><a class="nav-link" href="{% url 'home:log_out' %}" style="text-decoration: none; color: rgb(224, 60, 60); font-weight: 500;">Log Out</a>  </span>
                        </div>
                        <img src="https://wallpapercave.com/wp/wp7753511.png" alt="accounts" style="width: 100%;border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                    {% else %}
                    <div class="acc2">
                        <br>
                        <a href="{% url 'home:log_in' %}" style="text-decoration: none; color: rgb(100, 100, 241);"> Login </a> <br> <br>
                        <span style="background-color: brown; color: white; padding: 5px; border-radius: 5px;">Register</span> <br> <br>
                        <a href="{% url 'home:writer_register' %}" style="text-decoration: none; color: brown;"> As Writer </a> <br>
                        <a href="{% url 'home:buyer_register' %}" style="text-decoration: none; color: brown;"> As User </a> <br>
                        <a href="{% url 'home:artist_register' %}" style="text-decoration: none; color: brown;"> As Artist</a> <br>
                    </div>
                    <img src="https://wallpapercave.com/wp/wp7753511.png" alt="accounts" style="width: 100%;border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                    {% endif %}
                </div> <br>
                </div>
            </div>
            <div class="col-sm">
                <div class="contact">
                    <div class="contact1"> CONTACT US </div>
                    <div class="contact2"> <br>
                        <a href="https://wa.me/254743597479" target="_blank" style="text-decoration: none; font-weight: 500; color: rgb(43, 184, 43);"> WHATSAPP </a> 
                    </div>
                    <div class="contact2">
                        <a href="https://twitter.com/blue_cisco" target="_blank" style="text-decoration: none; font-weight: 500; color: rgb(43, 184, 43);">TWITTER</a>
                    </div>
                    <br>
                    <img src="https://wallpapercave.com/wp/wp8697562.jpg" alt="accounts" style="width: 100%;border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                </div> <br>
            </div>
        </div>
    </div>

    <div style="text-align: center;">
        {% if request.user.is_superuser %}
            <a href="{% url 'blog:create_category' %}"> <button class="btn btn-danger btn-sm">Category</button></a>
        {% endif %}
    </div>

    <div style="text-align: center; border-radius: 10px; margin-bottom: 100px;">
        <div class="tt">
            FREENTY WEBSITES
        </div> <br>
        <div style="padding-bottom: 10px;">
            <span class="linki">
                <a href="https://www.manna.freenty.com" target="_blank" style="text-decoration: none; color: black;"> MANNA.FREENTY.COM </a>
            </span>
            <br> <br>
            <span class="linki">
                <a href="https://www.lady.freenty.com" target="_blank" style="text-decoration: none; color: black;"> LADY.FREENTY.COM </a>
            </span>
            <br> <br>
            <span class="linki">
                <a href="https://www.gent.freenty.com" target="_blank" style="text-decoration: none; color: black;"> GENT.FREENTY.COM </a>
            </span>
            
        </div>
        <div class="tt">
            FREENTY VIDEOS
        </div>
        <div style="padding-bottom: 10px;"> <br>
            <span class="linki">
                <a href="https://www.youtube.com/channel/UChVKT2_ioZ8BTWVHyikIfkA" target="_blank" style="text-decoration: none; color: black;">YOUTUBE</a>
            </span>
        </div>
    </div>
    
</body>
</html>