blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from blog.views import blog_add

app_name = 'blog'
urlpatterns = [
    path('blog/add-blog/',views.add_blog,name='add_blog'),
    path('blog/add-topic/',views.add_topic,name='add_topic'),
    path('blog/topic/<int:id>/',views.topic_detail,name='topic_detail'),
    path('add-blog/',views.blog_add.as_view(),name='blog_add'),
    path('blog/<int:blogid>/preference/<int:userpreference>/',views.blogpreference,name='blogpreference'),
    path('blog/vote/<int:topicid>/preference/<int:userpreference>/',views.topicpreference,name='topicpreference'),
    path('blog/blog_list/',views.blog_list,name='blog_list'),
    path('blog/<category_slug>/',views.blog_list,name='blog_list_by_category'),
    path('blog/<int:id>/<slug>/',views.blog_detail,name='blog_detail'),
    path('my-blogs/',views.edit_list,name='edit_list'),
    path('archive-blog/<int:id>/',views.archive_blog, name='archive_blog'),
    path('publish-blog/<int:id>/',views.publish_blog, name='publish_blog'),
    path('edit-blog/<int:id>/',views.edit_blog, name='edit_blog'),
    path('create-category-blog/',views.create_category, name='create_category'),
]

home/shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from shop.views import art_add

app_name = 'shop'
urlpatterns = [
    path('add-art/',views.add_art,name='add_art'),
    path('art/add-art/',views.art_add.as_view(),name='art_add'),
    path('art/<int:artid>/preference/<int:userpreference>/',views.artpreference,name='artpreference'),
    path('art/art_list',views.art_list,name='art_list'),
    path('art/<category_slug>/',views.art_list,name='art_list_by_category'),
    path('art/<int:id>/<slug>/',views.art_detail,name='art_detail'),
    path('bidding/<int:id>/<slug>/',views.bidding,name='bidding'),
    path('art/bidding/<int:id>/<slug>/',views.bidding_detail,name='bidding_detail'),
    
]

legends/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'legends'
urlpatterns = [
    path('<int:id>/',views.legend_detail,name='legend_detail'),
    path('legend/<int:legendid>/preference/<int:userpreference>/',views.legendpreference,name='legendpreference'),
    path('legend-list',views.legend_list,name='legend_list'),
    
]

wasanii/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name = 'home'),
    path('',include(('home.urls','home'),namespace='home')),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path('',include(('legends.urls','legends'),namespace='legends')),
    path('',include(('orders.urls','orders'),namespace='orders')),
    path('',include(('shop.urls','shop'),namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Blog, Comment, Topic, TComment
from home.models import WriterProfile

class BlogAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(BlogAddForm, self).__init__(*args, **kwargs)
        writer = self.request.user.writerprofile
        self.fields['writer'].queryset = WriterProfile.objects.filter(user = self.request.user)
    class Meta:
        model = Blog
        fields = ['category','writer','title','content']

class BlogEditForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['category','title','content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body' : forms.Textarea(attrs={
                'rows': '5',
                'cols': '40',
                'maxlength': '600',
            }),
        }

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name','description']
        widgets = {
            'description' : forms.Textarea(attrs={
                'rows': '5',
                'cols': '40',
                'maxlength': '600',
            }),
        }

class TCommentForm(forms.ModelForm):
    class Meta:
        model = TComment
        fields = ['body']
        widgets = {
            'body' : forms.Textarea(attrs={
                'rows': '5',
                'cols': '40',
                'maxlength': '300',
            }),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.template import loader
from django.http import HttpResponse, Http404,HttpResponseRedirect
from .models import Category,Blog,Preference,Comment,Topic,TopicVote, TComment
from django.contrib.auth.decorators import login_required
from .forms import BlogAddForm, CommentForm,TopicForm, TCommentForm,BlogEditForm
from django.contrib.auth.models import User
from home.models import WriterProfile
from django.views.generic import CreateView 
from django.urls import reverse_lazy
from django.contrib.auth.models import User

def blog_list(request, category_slug=None):
    # get the list of all arts that can be bided on.
    template = loader.get_template('blog/list.html')
    category = None
    categories = Category.objects.all()
    blogs = Blog.objects.filter(status= 1)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        blogs = blogs.filter(category=category)
    
    context = {'category':category,
                'categories':categories,
                'blogs':blogs,}
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def blog_detail(request, id, slug):
    # show the detail of an individual blog that can be bided on.
    template = loader.get_template('blog/detail.html')
    blog = get_object_or_404(Blog,id=id,slug=slug)
    # count views
    blog.blog_views = blog.blog_views+1
    blog.save()
    comments = Comment.objects.filter(blog= blog)
    new_comment = None
    # Comment posted
    if request.method == 'POST': 
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.blog = blog
            new_comment.name = request.user
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {'blog':blog,'comments': comments,'new_comment': new_comment,'comment_form': comment_form}
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def edit_list(request):
    username = request.user
    try:
        profile = WriterProfile.objects.get(user=username)
        #profile_ = WriterProfile.objects.filter(user=username)
        #profile = WriterProfile.objects.get(user=username)
        blogs = Blog.objects.filter(writer=profile)
        context = {'profile':profile,'blogs':blogs,}
        template = loader.get_template('blog/edit_list.html')
        return HttpResponse(template.render(context,request))
    except WriterProfile.DoesNotExist:
        return HttpResponse('You are not registered as a writer.')


@login_required(login_url='/login/')
def archive_blog(request,id):
    blog = get_object_or_404(Blog,id=id)
    blog.status = 0
    blog.save()
    return redirect('blog:edit_list')

@login_required(login_url='/login/')
def publish_blog(request,id):
    blog = get_object_or_404(Blog,id=id)
    blog.status = 1
    blog.save()
    return redirect('blog:edit_list')

@login_required(login_url='/login/')
def edit_blog(request,id):
    blog = get_object_or_404(Blog,id=id)
    if request.method == 'POST':
        form = BlogEditForm(request.POST,request.FILES,instance=blog)
        if form.is_valid():
            form.save()
            return redirect('blog:edit_list')
    else:
        form = BlogEditForm(instance=blog)
    template = loader.get_template('blog/edit_blog.html')
    context = {'form':form}
    return HttpResponse(template.render(context,request)) 


@login_required(login_url='/login/')
def add_blog(request):
    # check if the user is an artist
    a = request.user
    b = WriterProfile.objects.filter(user=a).count()
    if b == 1:
        return redirect('blog:blog_add')
    else:
        return HttpResponse('Sorry.You are not registered as a writer.')
    
class blog_add(CreateView):
    # adding a blog
    model = Blog
    form_class = BlogAddForm
    template_name = 'blog/add_blog.html'
    success_url = reverse_lazy('blog:blog_list')
    def get_form_kwargs(self):
        kwargs = super(blog_add, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs 

@login_required(login_url='/login/')
def blogpreference(request,blogid, userpreference):
    if request.method == "POST":
        eachpost= get_object_or_404(Blog, id=blogid)
        aa = eachpost.id
        ss = eachpost.slug
        obj=''
        valueobj=''
        try:
            obj= Preference.objects.get(user= request.user, blog= eachpost)
            valueobj= obj.value #value of userpreference
            valueobj= int(valueobj)
            userpreference= int(userpreference)
            if valueobj != userpreference:
                obj.delete()
                upref= Preference()
                upref.user= request.user
                upref.blog= eachpost
                upref.value= userpreference
                if userpreference == 1 and valueobj != 1:
                    eachpost.likes += 1
                    eachpost.dislikes -=1
                elif userpreference == 2 and valueobj != 2:
                        eachpost.dislikes += 1
                        eachpost.likes -= 1
                upref.save()
                eachpost.save()
                return redirect('blog:blog_detail',id=aa,slug=ss)

            elif valueobj == userpreference:
                obj.delete()
                if userpreference == 1:
                    eachpost.likes -= 1
                elif userpreference == 2:
                    eachpost.dislikes -= 1
                eachpost.save()
                return redirect('blog:blog_detail',id=aa,slug=ss)
        except Preference.DoesNotExist:
            upref= Preference()
            upref.user= request.user
            upref.blog= eachpost
            upref.value= userpreference
            userpreference= int(userpreference)
            if userpreference == 1:
                eachpost.likes += 1
            elif userpreference == 2:
                eachpost.dislikes +=1
            upref.save()
            eachpost.save()                            
            return redirect('blog:blog_detail',id=aa,slug=ss)

    else:
        eachpost= get_object_or_404(Blog, id=blogid)
        return redirect('home')

@login_required(login_url='/login/')
def add_topic(request):
    # show the detail of an individual blog that can be bided on.
    template = loader.get_template('blog/add_topic.html')
    topics = Topic.objects.all()
    new_topic = None
    # Comment posted
    if request.method == 'POST':
        topic_form = TopicForm(data=request.POST)
        if topic_form.is_valid():
            # Create Comment object but don't save to database yet
            new_topic = topic_form.save(commit=False)
            # Assign the current post to the comment
            new_topic.proposer = request.user
            # Save the comment to the database
            new_topic.save()
    else:
        topic_form = TopicForm()
    context = {'topics':topics,'new_topic': new_topic,'topic_form': topic_form}
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def topic_detail(request, id):
    # show the detail of an individual blog that can be bided on.
    template = loader.get_template('blog/topic_detail.html')
    topic = get_object_or_404(Topic,id=id)
    comments = TComment.objects.filter(topic= topic)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        t_comment_form = TCommentForm(data=request.POST)
        if t_comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = t_comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.topic = topic
            new_comment.name = request.user
            # Save the comment to the database
            new_comment.save()
    else:
        t_comment_form = TCommentForm()
    context = {'topic':topic,'comments': comments,'new_comment': new_comment,'t_comment_form': t_comment_form}
    return HttpResponse(template.render(context,request))

@login_required(login_url='/login/')
def topicpreference(request,topicid, userpreference):
    if request.method == "POST":
        eachpost= get_object_or_404(Topic, id=topicid)
        aa = eachpost.id
        obj=''
        valueobj=''
        try:
            obj= TopicVote.objects.get(user= request.user, topic= eachpost)
            valueobj= obj.value #value of userpreference
            valueobj= int(valueobj)
            userpreference= int(userpreference)
            if valueobj != userpreference:
                obj.delete()
                upref= TopicVote()
                upref.user= request.user
                upref.topic= eachpost
                upref.value= userpreference
                if userpreference == 1 and valueobj != 1:
                    eachpost.likes += 1
                    eachpost.dislikes -=1
                elif userpreference == 2 and valueobj != 2:
                        eachpost.dislikes += 1
                        eachpost.likes -= 1
                upref.save()
                eachpost.save()
                return redirect('blog:topic_detail',id=aa)

            elif valueobj == userpreference:
                obj.delete()
                if userpreference == 1:
                    eachpost.likes -= 1
                elif userpreference == 2:
                    eachpost.dislikes -= 1
                eachpost.save()
                return redirect('blog:topic_detail',id=aa)
        except TopicVote.DoesNotExist:
            upref= TopicVote()
            upref.user= request.user
            upref.topic= eachpost
            upref.value= userpreference

blog/templates/blog/add_blog.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
Add Blog
{% endblock %}
{% block content %}
<div class="container">
    {% load widget_tweaks %}
    <form method="post" novalidate enctype="multipart/form-data" action=".">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %}
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
    
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
            {% else %}
            {% render_field field class="form-control" %}
            {% endif %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 15px;">Save</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/add_topic.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
Topic
{% endblock %}
{% block content %}
<div class="container">
    <div style="margin-bottom: 10px;">
        {% if new_topic %}
        <div class="alert alert-success" role="alert">
            Your proposed topic is viable for voting.
        </div>
        {% else %}
        <h3>Propose a topic</h3>
        <form method="post" style="margin-top: 1.3em;" action=".">
            {{ topic_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        {% endif %}
    </div>
    <div>
        {% if topics %}
        <p>Proposed topics</p>
        {% for topic in topics %}
        <div class="text-dart">
            <span>{{topic.name}}</span> <br>
            Proposed by: <span style="color: grey;">{{topic.proposer}}</span>
        </div>
        <div>
            <a href="{{topic.get_topic_url}}">Vote</a> <br>
            Up votes <span style="color: brown;">{{topic.likes}}</span> <br>
            Down votes <span style="color: rgb(230, 217, 47);">{{topic.dislikes}}</span>
        </div>
        <hr>
        {% endfor %}
        {% else %}
            <p>Propose a topic for writers to write about.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
        <title>{% block title %}Blogs{% endblock %}</title>
        <script>
            /* Set the width of the side navigation to 250px */
            function openNav() {
                document.getElementById("mySidenav").style.width = "250px";
                }
            /* Set the width of the side navigation to 0 */
            function closeNav() {
                document.getElementById("mySidenav").style.width = "0";
                }
        </script>
        <style>
            /* The side navigation menu */
            .sidenav {
                 height: 100%; /* 100% Full-height */
                 width: 0; /* 0 width - change this with JavaScript */
                position: fixed; /* Stay in place */
                z-index: 1; /* Stay on top */
                top: 0; /* Stay at the top */
                left: 0;
                background-color: #cccde7; /* Black*/
                overflow-x: hidden; /* Disable horizontal scroll */
                padding-top: 60px; /* Place content 60px from the top */
                margin-top: 65px;
                transition: 0.5s; /* 0.5 second transition effect to slide in the sidenav */
                border-top-right-radius: 5px;
                }

            /* The navigation menu links */
            .sidenav a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 15px;
                color: #312f2f;
                display: block;
                transition: 0.3s;
                }

            /* When you mouse over the navigation links, change their color */
            .sidenav a:hover {
                color: #6e326b;
                }

            /* Position and style the close button (top right corner) */
            .sidenav .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
                color: red;
                }

            /* Style page content - use this if you want to push the page content to the right when you open the side navigation */
            #main {
                transition: margin-left .5s;
                padding: 20px;
                }

            /* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
            @media screen and (max-height: 450px) {
                .sidenav {padding-top: 15px;}
                .sidenav a {font-size: 18px;}
                }
            .items{
                border: 1px blue solid; 
                background-color: white;
                padding: 3px;
                margin-bottom: 5px; 
                border-radius: 3px;
                transition: all .4s ease-in-out;
                box-shadow: 0 0 25px 0 rgba(20, 27, 202, .17);
            }
            .items:hover {
                box-shadow: 0 0 25px 0 rgba(20, 27, 201, .05);
                cursor: pointer;
                background-image: linear-gradient(-45deg, #d3cfeb 0%, #bbd0e2 100%)
            }
            .items:focus {
                box-shadow: 0 0 25px 0 rgba(20, 27, 201, .05);
                cursor: pointer;
                background-image: linear-gradient(-45deg, #ccc7e6 0%, #bed2e4 100%)
            }
            /*Floating Back-To-Top Button*/
    #topBtn {
        position: fixed;
        bottom: 10px;
        float: right;
        right: 10px;
        max-width: 40px;
        width: 100%;
        font-size: 12px;
        border-color: rgba(85, 85, 85, 0.2);
        background-color: rgb(100,100,100);
        padding: 3px;
        border-radius: 4px;
    }
    .dits{
        position: fixed;
        bottom: 10px;
        float: left;
        left: 10px;
        max-width: fit-content;
        border-color: rgba(85, 85, 85, 0.2);
        background-color: rgb(252, 246, 246);
        padding: 3px;
        border-radius: 4px;
    }
/*On Hover Color Change*/
    #topBtn:hover {
        background-color: #7dbbf1;
    }
    .all{
        width: 100%;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }
        </style>
    </head>
    <body class="container-fluid bg-light">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top .navbar-expand{-sm|-md|-lg|-xl|-xxl}">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BLOG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog_list' %}">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:add_blog' %}" >Add Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:edit_list' %}" >My Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:add_topic' %}" >Propose</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:art_list' %}" >Arts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'legends:legend_list' %}">Legends</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:home' %}" >Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div style="padding-top: 55px;"></div>
        <div id="content";class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
        <button id="topBtn"><a href="#top" style="color: white; text-decoration: none;">Top</a></button>
    </body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
{% if blog %}{{ blog.title }}{% else %}Blog{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail container">
  <span style="font-weight: 500; font-size: larger; color: rgb(218, 40, 40);">{{ blog.title|title }} </span> <br>
  <div class="container">
    {{ blog.content|linebreaks }}
  </div>
  <div>
    <a href="#" onClick="document.getElementById('likebutton').submit()" style="text-decoration: none;">Like </a> {{blog.likes}} Likes 
    <a href="#" onClick="document.getElementById('dislikebutton').submit()" style="text-decoration: none;">Dislike </a> {{blog.dislikes}} Dislikes
    <form id="likebutton" method="POST" action="/blog/{{blog.id}}/preference/1/">
        {% csrf_token %}
        <input type="hidden">
    </form>
    <form id="dislikebutton" method="POST" action="/blog/{{blog.id}}/preference/2/">
        {% csrf_token %}
        <input type="hidden">
    </form>
</div>
  <div style="margin-bottom: 70px;">
    <span style="color: rgb(143, 40, 40);">{{ comments.count }} comments</span> <br>
    {% if comments %}
    {% for comment in comments %}
        <div class="comments" style="padding: 1px;">
          <div class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">{{ comment.created_on }}</span> <br>
            {{ comment.body | linebreaks }}
            <hr>
          </div>
          
        </div>
        {% endfor %}
        {% else %}
        <p>Comment on this post.</p>
        {% endif %}
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Thank you for your opinion
        </div>
        {% else %}
        <h3>Leave a comment</h3>
          <form method="post" style="margin-top: 1.3em;" action=".">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        {% endif %}
  </div>
  <div class="dits">
    <span style="font-weight: 500;">Writer: </span><a href="{{blog.writer.get_writer_detail}}" style="text-decoration: none;">{{ blog.writer }}</a> <br>
    <span style="font-weight: 500;">Category:</span> <a href="{{ blog.category.get_absolute_url }}" style="text-decoration: none;">{{ blog.category }}</a>
  </div>

</div>

{% endblock %}

blog/templates/blog/edit_blog.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
Edit Blog
{% endblock %}
{% block content %}
<div class="container">
    {% load widget_tweaks %}
    <form method="post" novalidate enctype="multipart/form-data" action=".">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
        {% endfor %} 
        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
    
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
            {% else %}
            {% render_field field class="form-control" %}
            {% endif %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" style="margin-top: 15px;">Save</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/edit_list.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}
{% if blog %}{{ blog.title }}{% else %}Blog{% endif %}
{% endblock %}
{% block content %}
<div class="container">
    <div>
        <h4>Blogs by {{profile.user}}</h4>
    </div>
    <div>
        {% if blogs %}
            {% for blog in blogs %}
                <div>
                    <span style="color: blue;">Title</span> <br>
                    <span style="color: black; font-size: large; font-weight: 500;">{{ blog.title }} </span><br>
                    {% if blog.status == 0 %}
                        <a href="{{ blog.publish_blog_url }}"> <button class="btn btn-success"> Publish</button></a>&nbsp&nbsp 
                    {% else %}
                        <a href="{{ blog.archive_blog_url }}"> <button class="btn btn-danger"> Archive</button></a>&nbsp&nbsp 
                    {% endif %}
                    
                    <a href="{{ blog.edit_blog_url }}"> <button class="btn btn-info"> Edit</button></a>&nbsp&nbsp 
                    
                    <a href="{{ blog.get_blog_url }}"><button class="btn btn-primary"> Read </button></a>&nbsp&nbsp 
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <p>You have not posted any blog yet</p>
        {% endif %}
    </div>
</div>
{% endblock %}